export const INDICATOR_DOCUMENT_STEMS: Record<string, string> = {
  "infraestructura-001": "rex_reconocimiento_oficial",
  "infraestructura-002": "certificado_recepcion_final_obras",
  "infraestructura-003": "certificado_autorizacion_sanitaria",
  "infraestructura-004": "cert_autorizacion_manipulacion_alimentos",
  "infraestructura-005": "contrato_dominio_vigente",
  "infraestructura-006": "letrero_establecimiento_ro",
  "infraestructura-007": "plan_integral_seguridad_escolar_pr",
  "infraestructura-008": "acta_comite_seguridad_escolar",
  "infraestructura-009": "medidas_prevencion_riesgos",
  "infraestructura-010": "sello_verde_sec",
  "infraestructura-011": "protocolo_accidentes_escolares_pr",
  "infraestructura-012": "protocolo_emergencias",
  "infraestructura-013": "comite_paritario_pr",
  "infraestructura-014": "cumplimiento_m2_infraestructura",
  "asistencia-001": "libro_registro_salida_alumnos_foliado",
  "asistencia-002": "libro_clases_curso_digital",
  "asistencia-003": "declaracion_asistencia_mensual",
  "asistencia-004": "registro_matricula",
  "asistencia-005": "estructura_cursos",
  "asistencia-006": "libro_retiros",
  "asistencia-007": "firmas_docentes_syscol",
  "asistencia-008": "tiene_excedentes",
  "asistencia-009": "resolucion_excedentes",
  "asistencia-010": "autorizacion_sobrecupos",
  "temas-laborales-001": "titulo_representante_legal",
  "temas-laborales-002": "declaracion_set12_personal",
  "temas-laborales-003": "titulos_docentes_asistentes",
  "temas-laborales-004": "autorizacion_docentes",
  "temas-laborales-005": "titulo_habilitacion_docente_pie",
  "temas-laborales-006": "antecedentes_representante_legal",
  "temas-laborales-007": "antecedentes_trabajadores",
  "temas-laborales-008": "licenciatura_laboral_asistentes",
  "temas-laborales-009": "idoneidad_psicologica_asistentes",
  "temas-laborales-010": "idoneidad_profesores_religion",
  "temas-laborales-011": "idoneidad_moral_personal",
  "temas-laborales-012": "contratos_trabajo_anexos",
  "temas-laborales-013": "distribucion_carga_horaria_docente",
  "temas-laborales-014": "colegio_cuenta_trabajadores_extranjeros",
  "temas-laborales-015": "documentacion_extranjeros",
  "temas-acad-micos-001": "proyecto_educativo_institucional",
  "temas-acad-micos-002": "ultima_jec_aprobada_deprov",
  "temas-acad-micos-003": "evidencia_horas_tp",
  "temas-acad-micos-004": "certificado_ingreso_pie",
  "temas-acad-micos-005": "plan_inclusion_vigente",
  "temas-acad-micos-006": "plan_desarrollo_docente",
  "temas-acad-micos-007": "acompanamiento_autorizacion_apoderado",
  "temas-acad-micos-008": "certificado_nacimiento",
  "temas-acad-micos-009": "informes_familia",
  "temas-acad-micos-010": "matricula_sin_parvularia",
  "temas-acad-micos-011": "certificados_promocion_escolar",
  "temas-acad-micos-012": "carpetas_pie_estudiantes",
  "temas-acad-micos-013": "reglamento_evaluacion_difusion",
  "temas-acad-micos-014": "actas_consejo_escolar",
  "temas-acad-micos-015": "consejo_profesores",
  "temas-acad-micos-016": "consejo_apoderados",
  "temas-acad-micos-017": "formacion_tecnico_profesional",
  "temas-acad-micos-018": "beneficios_practica_profesional",
  "temas-acad-micos-019": "reglamento_practica_tp",
  "temas-acad-micos-020": "resolucion_especialidad_t_p",
  "temas-acad-micos-021": "expediente_titulacion_tp",
  "formaci-n-y-convivencia-001": "plan_gestion_convivencia_escolar",
  "formaci-n-y-convivencia-002": "plan_formacion_ciudadana",
  "formaci-n-y-convivencia-003": "plan_afectividad_sexualidad_genero",
  "formaci-n-y-convivencia-004": "capacitacion_convivencia_escolar",
  "formaci-n-y-convivencia-005": "nombramiento_encargado_convivencia",
  "formaci-n-y-convivencia-006": "reglamento_interno_evidencia_difusion",
  "formaci-n-y-convivencia-007": "constitucion_consejo_escolar",
  "formaci-n-y-convivencia-008": "base_consejo_escolar",
  "formaci-n-y-convivencia-009": "sistema_admision_escolar",
  "formaci-n-y-convivencia-010": "documento_capacidad_total_colegio",
  "formaci-n-y-convivencia-011": "documento_estructura_curso",
  "formaci-n-y-convivencia-012": "comprobante_registro_cupos",
  "formaci-n-y-convivencia-013": "matricula",
  "formaci-n-y-convivencia-014": "libro_registro_publico",
  "formaci-n-y-convivencia-015": "certificado_traslado_estudiantes_retiran",
  "formaci-n-y-convivencia-016": "comprobante_matricula",
  "formaci-n-y-convivencia-017": "contrato_servicios_educacionales",
  "formaci-n-y-convivencia-018": "cupos",
  "otros-001": "letrero_ley_tea",
  "otros-002": "cuenta_publica_realizada",
  "otros-003": "base_cuenta_publica"
};

function normalizeFallbackStem(value: string) {
  return String(value ?? '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
    .toLowerCase() || 'indicador';
}

export function getIndicatorDocumentStem(indicatorId: string, fallbackName: string) {
  return INDICATOR_DOCUMENT_STEMS[indicatorId] ?? normalizeFallbackStem(fallbackName);
}
